language: go
go:
  - 1.6

branches:
  only:
  - source

sudo: false

install:
  - go get github.com/spf13/hugo

before_script:
- git config --global user.name 'Travis CI on behalf of Konstantin Pavlov'
- git config --global user.email 'git@konstantinpavlov.net'

script:
  - hugo

after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add -t gh-pages origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m "Site updated `date`"
- git branch -m gh-pages
- git push -q -u origin gh-pages
